version: '3.8'

services:
  web:
    image: php:8.1-apache
    container_name: alama_YADPEB
    volumes:
      - ./:/var/www/html
    environment:
      APACHE_RUN_USER: www-data
      APACHE_RUN_GROUP: www-data
      SERVER_NAME: alama.host
    restart: always
    networks:
      - caddy
    labels:
      caddy: alama.host
      caddy.reverse_proxy: "{{upstreams 80}}"

networks:
  caddy:
    external: true
